### ISSUE TITLE
Why this, instead of using CRaSH?

### ISSUE THREAD

**Issue by apatrida** [vert-x3/vertx-shell#3]
There was a shell for vertx 2 that was based on CRaSH.  this looks like a custom term library, why not on CRaSH?  

(this is curiosity question since I'm about to write a REPL interface to an app)

**Comment by vietj** [comment]
really need to open an issue for this :-) ?

a couple of reasons (non exhaustive):

1/ CRaSH developed its own connectors based on Apache SSHD, Telnetd. Apache SSHD came with Mina, Telnetd was not really supported anymore. At the same time when I joined Vert.x team I started to write a new Telnet server implementation based on Netty because Telnetd was quite old and also not supported anymore. Then I got the idea to make a lib https://github.com/termd/termd in the Vert.x spirit that only focus on doing Term things (that is no command, shell concepts, etc...). This library is much more easier to embed than CRaSH and also all network connectors (Telnet, SSH) are based on Netty that is embedded already in Vert.x 3. 

2/ second reason and it's an important one, vertx-shell based on CRaSH would be quite difficult to achieve correctly because CRaSH is designed to be blocking and Vert. So vertx-shell is quite well integrated with Vert.x in term of programming model (non blocking, context behavior). Also Termd is written in non blocking, event style which helps to develop a shell based on that.

3/ Vertx-shell leverages also the polyglot capabilties of Vert.x, which makes easy to write vertx-shell command in any language. CRaSH got this polyglot aspect too but using its own mechanism (obviously) and at the end it was only providing Groovy commands, not JS, not Ruby. Obviously they could have been developed. But rather reuse what already exist in Vert.x 3 today.

that being said, Vertx-shell does not aim to be like CRaSH (which is a general purpose tool for the JVM) and rather focus on providing the best shell for Vert.x 3.

finally, obviously there could have been good reasons to reuse CRaSH and embed it, but it just came naturally this way :-)

**Comment by vietj** [comment]
note : CRaSh should somehow be refactored to follow non blocking style as it has already some aspect of this, specially in the pipeline of commands, CRaSH style is:

```
public void provide(T t) {
  // Do something with T
  U u = doSomethingWith(t);
  next.provide(u);
}
```

what does not work is the whole pipe line execution (internal detail). I believe it should be refactored this way. More over it should refactor the pipeline on reactive streams library as this is really similar behavior.

**Comment by vietj** [comment]
other note to @apatrida if you want to make your own REPL and only care about Terminal, you should consider using Termd as it provides a much better terminal implementation than the one in CRaSH (but it's normal, I wrote it :-) )

**Comment by apatrida** [comment]
Termd but with local console in/out instead of telnet or ssh.   

Thanks for all the info.

**Comment by vietj** [comment]
open an issue for locale console in termd project.

**Comment by apatrida** [comment]
I wrote a well crafted lengthy and expressive request for local console there.   Thanks
